import { Persona } from "./models/Persona.js";

// ── Color palette offered to users when building custom personas ──────────────
export const PERSONA_COLORS = [
  "#4A90D9", // blue  (Operator default)
  "#3DAA84", // green (Futurist default)
  "#C27B3A", // amber
  "#9B5DE5", // violet
  "#E84855", // red
  "#F4A261", // orange
];

// ── ElevenLabs voices available in the persona builder ────────────────────────
export const VOICE_OPTIONS = [
  { id: "Xb7hH8MSUJpSbSDYk0k2", label: "Alice — British, assertive (F)" },
  { id: "IKne3meq5aSn9XLyUdCD", label: "Charlie — confident, energetic (M)" },
  { id: "onwK4e9ZLuTAKqWW03F9", label: "Daniel — British, measured (M)" },
  { id: "pNInz6obpgDQGcFmaJgB", label: "Adam — deep, authoritative (M)" },
  { id: "21m00Tcm4TlvDq8ikWAM", label: "Rachel — calm, clear (F)" },
  { id: "AZnzlk1XvdvUeBnXmlld", label: "Domi — strong, direct (F)" },
  { id: "ThT5KcBeYPX3keUQqHPh", label: "Dorothy — British, warm (F)" },
  { id: "TxGEqnHWrfWFTfGW9XjX", label: "Josh — casual, young (M)" },
];

// ── Built-in personas — kept as defaults and demo examples ───────────────────
// Stances are pre-written; custom personas get theirs generated by Claude.
export const PRESET_PERSONAS = {
  A: new Persona({
    name: "The Operator",
    description: "COO with 20 years running large enterprises. Pragmatic, direct, and tired of AI hype cycles. Skeptical of every claim until proven.",
    color: "#4A90D9",
    voiceId: "Xb7hH8MSUJpSbSDYk0k2",
  }),
  B: new Persona({
    name: "The Futurist",
    description: "Chief AI Officer who lives and breathes digital transformation. Systems-first thinker who believes AI reshapes everything.",
    color: "#3DAA84",
    voiceId: "IKne3meq5aSn9XLyUdCD",
  }),
};

// ── Narrative arc injected into the final turn ────────────────────────────────
export const CLOSING_ARCS = [
  "You want to land one question they'll have to sit with long after this conversation ends. Make it sharp and specific.",
  "You're less combative than when you started — not converted, just more aware of the weight of the other side. Let that show slightly as you close.",
  "You want to reframe the whole debate on your way out — name what the real underlying question actually is beneath all of this.",
  "You're closing on pragmatism. Less about who's right, more about what actually needs to happen next in the real world.",
  "You're done with abstraction. End with one concrete specific — a scenario, a number, a real example that cuts through everything.",
  "Make sure your core point landed. One final clear statement, nothing new, just the sharpest version of what you've been saying.",
  "You're closing with more respect for the other side than you started with, even though your position hasn't changed. Let that come through.",
  "You want to name what this conversation actually revealed — not just about the topic, but about how these decisions get made.",
];

// ── Preset debate topics ──────────────────────────────────────────────────────
export const TOPICS = [
  "Should organizations replace human decision-makers with AI in high-stakes situations?",
  "Is the risk of moving too slowly on AI greater than the risk of moving too fast?",
  "Can AI ever be trusted to manage people, or is that a line we should never cross?",
  "Will AI create an accountability gap that neither leadership nor regulators know how to close?",
  "Is 'AI strategy' just digital transformation rebranded, or is this genuinely different?",
  "Will AI widen the gap between market leaders and everyone else, or level the playing field?",
  "Should organizations share AI failures publicly the way aviation shares crash reports?",
  "Is the real barrier to AI adoption technology, culture, or regulation?",
  "Can you build a high-trust organization if AI is making decisions employees can't see or challenge?",
  "Is owning AI inside an organization a leadership problem, a technology problem, or both?",
  "Is 'responsible AI' a meaningful commitment or a PR exercise?",
  "Will the organizations that wait for AI to mature end up too far behind to catch up?",
];

export function pick(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}
